apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItem
  template:
    metadata:
      labels:
        app: MenuItem
    spec:
      containers:
      - name: menuitem
        image: samplectr.azurecr.io/menuitemrepos:latestmenu
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: menuitem
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItem